
package com.revature.tutorial;
import java.sql.SQLException;
import java.util.List;
import java.sql.Date;


import com.revature.dao.StudentDAO;
import com.revature.dto.StudentDTO;
import com.revature.model.Student;
import com.revature.util.Callable;

public class JDBCApp2 {
	
	public static void main(String args[]) {
		
		Callable call = new Callable();
		StudentDAO stuDAO = new StudentDAO();
		
		try {
//			List<Student> rsts = stuDAO.getAllStudents();
//			call.println(rsts);
//			
//			Student jane = stuDAO.getStudentById(1);
//			call.println(jane);
			
			//student to be added
			//Student stu = new Student(0, "Miracle", "Obeta", "Junior", 21, new Date(2018-02-11));
			//Student inserted = stuDAO.addStudent(stu);
			//call.println(inserted);
			
			//stu takes in a StudentDTO object as input arguments and returns a student object
			//contain the record that was inserted into the database (w/ autogenerated ID)
			StudentDTO stu = new StudentDTO("Miracle", "Obeta", "Junior", 21, new Date(2018-02-11));
			Student inserted = stuDAO.addStudent(stu);
			call.println(inserted);
			
		} catch (SQLException err) {
			err.printStackTrace();
		}
	}
}

